### ISSUE TITLE
menu from array 

### ISSUE THREAD

**Issue by atherdon** [atherdon/bebe-grocery#40]
https://github.com/atherdon/bebe-grocery/blob/master/src/components/Menu.js

So we should have file at folder `data`. that file will have similar look:
https://github.com/ChickenKyiv/recipe-search-react/blob/master/src/data/allergies.js

Check files `first/second` - we have some work started, but didn't finished.
menu items we'll replace with loop.

**Comment by atherdon** [comment]
@smob123 can you help me with this task?

**Comment by atherdon** [comment]
check the menu file(component) - so each item have title, link, class.
this should be stored at file. also check files from 'data' folder - so
you'll get more ideas about how to do it.


On 30-May-2018 at 02:37 PM, smob123 wrote:


for sure, so what is the content you want to have inside of the array?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/atherdon/bebe-grocery/issues/40#issuecomment-393187167>,
or mute the thread

**Comment by smob123** [comment]
alright, that sounds simple enough.
I will start working on it on Friday, because I have a midterm coming up

**Comment by atherdon** [comment]
sounds good! in mean time i'll try to take a look at your code repository.


On 30-May-2018 at 04:23 PM, smob123 wrote:


alright, that sounds simple enough.
I will start working on it on Friday, because I have a midterm coming up

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/atherdon/bebe-grocery/issues/40#issuecomment-393225304>,
or mute the thread

**Comment by smob123** [comment]
I pushed the changes, do they look alright?

**Comment by atherdon** [comment]
yes, send a message in your pull request
